"""add_foreign_keys_to_user_permissions

Revision ID: 52054d60432c
Revises: f29df2f97962
Create Date: 2026-03-08 00:09:22.330880
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52054d60432c'
down_revision: Union[str, None] = 'f29df2f97962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_permissions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_permissions', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_permissions', type_='foreignkey')
    op.drop_constraint(None, 'user_permissions', type_='foreignkey')
    # ### end Alembic commands ###
